spring:
  application:
    name: Atlas-Project-Service

  datasource:
    url: jdbc:postgresql://localhost:5432/atlas_projectservice
    username: brunocase
    password: case

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

api:
  security:
    token:
      secret: "OUJWeHM3OUJMPi80SzQ7O0tsQWFNZHtYOmopYWVJVFYK"

server:
  port: 8083

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

      logging:
        level:
          com.netflix.discovery: DEBUG
          org.springframework.cloud.netflix.eureka: DEBUG